Fj 2024 lesson 2
SeeXWH/-fj_2024 pull request #2
Opened 2024-09-03 21:36 UTC by SeeXWH

2024-09-06 16:52 UTC, engarik requested changes
В целом всё хорошо, нужно поправить
1. Форматирование
2. Добавить использование лога уровня debug

Не забывай про автоформатирование в IDEA, часто выручает:
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2024-09-06 16:52 UTC, engarik commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/java,intellij,maven
Нужно поправить gitignore, директорий .idea и .gradle не должно быть в git

2024-09-06 16:52 UTC, engarik commented on src/main/java/org/example/City.java
> +    import lombok.*;
Лучше всегда заменять wildcard импорты на явные

2024-09-06 16:52 UTC, engarik commented on src/main/java/org/example/City.java
> +    package org.example;
У тебя весь файл с отступом в таб, так не надо)

2024-09-06 16:52 UTC, engarik commented on src/main/java/org/example/Coords.java
> +import lombok.*;
Тут тоже

2024-09-06 16:52 UTC, engarik commented on src/main/java/org/example/Main.java
> +    private static final Logger logger = LoggerFactory.getLogger(Main.class);
Можно заменить на аннотацию `@Slf4j`из lombok
https://projectlombok.org/features/log

2024-09-06 16:52 UTC, engarik commented on src/main/java/org/example/Main.java
> +                    System.out.println(jsonString);
Лучше не комбинировать использование логгирование и stdout, а использовать что-то одно (логгер)

2024-09-11 18:49 UTC, engarik commented
Такс, ты накоммитил лишнего, давай постараюсь помочь тебе это разгрести. Ничего страшного, такое бывает.

Первое: Поскольку ты обновил gitignore уже после того как файлы попали в гит, то они все равно уже залиты в ветку и сами собой не пропадут из неё, нужно выполнить некоторую манипуляцию.
Самый просто вариант:
1. На всякий случай сделай копию директории с проектом где-то отдельно.
2. Удали из файла gitignore директории которые хочешь убрать из ветки (в твоем случае .gradle, .idea)
3. Заккомить изменения (пушить не надо)
4. Локально удали эти директории (не забудь их перед этим сохранить где-то)
5. В гите должно отобразится что ты удалил эти файлы, сделай коммит.
6. Верни в gitignore директории .idea и .gradle
7. Верни сами директории и произведи коммит, проверь что ничего лишнего не попало 
8. Легкий вариант - запушь изменения, сложный вариант - сделай squash последних коммитов и запушь измения
9. Profit - ты молодец.

Второе - надо разделить вторую и третью домашки
1. Переключись на ветку main.
2. Отведи новую ветку от main для 3-ей домашки
3. Сделай cherry-pick коммита с изменениями из 3-ей домашки в новую ветку
4. Запушь изменения
5. Из ветки #2 удали измения 3-ей домашки, лучше всего через revert commit

Попробуй сделать так, если не получится, всегда можно просто перенести файл в отдельную ветку
!Однако! в реальных проектах так сделать очень сложно и нужно уметь работать с гитом

2024-09-11 18:51 UTC, engarik commented
Вторую я принял, но третью буду смотреть после того как поправишь
Буду вопросы - пиши

2024-09-24 19:00 UTC, engarik commented
Получится разобраться? Нужна помощь?

2024-09-24 20:06 UTC, SeeXWH commented
все же я не до конца понял, и мне нужна помощь....

2024-10-08 19:18 UTC, merged